### ISSUE TITLE
Conda install is depending on MinGW on win64

### ISSUE THREAD

**Issue by christian34** [openalea-incubator/caribu#30]
When installing caribu with conda on win64 (conda install -c alinea.caribu), two errors occur at run time:
- libstdc++6.dll and libgcc_s_dw2-1.dll are mising

If I install mingw with conda, only libstdc++6.dll is found, but  libgcc_s_dw2-1.dll is still missing

If I install MinGW on the machine using the standard distrib, then adding MinGW/bin to the path. everything is okay

Any clue to simplify /robustify this install ?

**Comment by pradal** [comment]
We can test with gcc from msys:

`conda install libpython m2w64-toolchain -c msys2`

**Comment by pradal** [comment]
Another solution may be:
-static-libgcc -static-libstdc++

**Comment by christian34** [comment]
This may also probably be linked to the non-declaration of conda installed compiler by sconsx (see PR 47 on openalea/sconsx)

**Comment by christian34** [comment]
@pradal @fredboudon 
A working version of caribu can be now be build with my machine under the following environment:
 - no MINGW or VisualStudio installed
 - require mingwpy for build
- use conda-build

For now I have uploaded this working win64.tar.bz2 for alinea.caribu 7.0.5 on openalea chanel

Still under appveyor, using the same meta.yml, a non functional version is build (dll error, as reported in this issue), even is the path to gcc passed to scons seems okay (Force environment with compiler options : {'tools': ['mingw'], 'ENV': {'TMP': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1', 'PATH': ['C:\\Miniconda\\conda-bld\\alinea.caribu_1542033877588\\_h_env\\Scripts\\']}})

I suspect that there is still some interaction with either MINGW / VisualStudio lib/dll pre-installed on the appveyor virtual machine. 

To be continued....

**Comment by pradal** [comment]
Sure.

Once you have found the path of the compiler, you have to inform scons
which one to use :

CC, LD, CXX and all the compiler variables has to be set to the compiler.

This need to be added to sconsx when compiler is set.

Cheers

Ch.


Le 12/11/2018 à 17:03, Christian Fournier a écrit :

**Comment by pradal** [comment]
Solved using : 
    
    env = Environment(options=options, ENV = {'PATH' : os.environ['PATH']}) in SConstruct

and

    m2w64-toolchain with conda
