### ISSUE TITLE
Virtual Sensors Option

### ISSUE THREAD

**Issue by dicombes** [openalea-incubator/caribu#33]
How can be the Virtual Sensors option "-C" of Caribu available ?

**Comment by dicombes** [comment]
Now Virtual sensors option are available in the updated Caribu. However, it doesn't work yet with the option "infinite=True"

**Comment by dicombes** [comment]
Now Virtual sensors option are available in the updated Caribu. However, it doesn't work yet with the option "infinite=True"

**Comment by pradal** [comment]
Same issue that #42
