### ISSUE TITLE
GLIBC_2.29 for periodise

### ISSUE THREAD

**Issue by RamiALBASHA** [openalea-incubator/caribu#51]
Dear all,

I'm getting this error when trying to run caribu on an ubuntu machine (named "modulor"):

    CaribuRunError: periodise: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by periodise)

Caribu version: 8.0.10 installed from openalea3
OS : Ubuntu 18.04.3 LTS
Python:  3.9.15

Any idea for a solution?

**Comment by pradal** [comment]
Seems to be a problem with the glibc version
Can you check version of glibc by running `ldd --version`?

**Comment by pradal** [comment]
Some insight here?
https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host/44710599#44710599

**Comment by RamiALBASHA** [comment]
> ldd --version
(Ubuntu GLIBC 2.27-3ubuntu1.5)

**Comment by RamiALBASHA** [comment]
> Some insight here? https://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host/44710599#44710599

It looks like a problem touching the binaries of the OS. I would rather not do that since I'm working on a shared server.

**Comment by pradal** [comment]
Have you tested something like:
```bash
sudo apt install libc-bin=2.29 libc6=2.29
```

**Comment by christian34** [comment]
I see two solutions:
- compile caribu on an old ubuntu flavor (don't know how easy this is), or conda build caribu from sources on modulor
- upgrade modulor to new ubuntu LTS, that has a compliant libc : I do not know how smooth such an update is for users

I will probably go through solution 2, execpt if olution 1 is easy (eg try a loccal conda build ?)

**Comment by pradal** [comment]
I think a fresh conda build on modulor is the simpliest

git clone
conda build
conda install --local

**Comment by RamiALBASHA** [comment]
It looks like a beginning of a cascade of other issues, `conda build .` in caribu gives:


    Unsatisfiable dependencies for platform linux-64: {'openalea.sconsx', 'openalea.deploy'}

**Comment by pradal** [comment]
No.
just use 
    conda build . -c openalea3 -c conda-forge

**Comment by RamiALBASHA** [comment]
> No. just use conda build . -c openalea3 -c conda-forge

That worked for installing sconsx and deploy but still need the glibc 2.29.

**Comment by RamiALBASHA** [comment]
> No. just use
> 
> ```shell
> conda build . -c openalea3 -c conda-forge
> ```

Did not work neither.
The issue was solved by upgrading ubuntu to v. 20.04 LTS.
