### ISSUE TITLE
Workflow nodes have been moved

### ISSUE THREAD

**Issue by pradal** [openalea-incubator/caribu#8]
Some nodes have been moved in caribu/workflow.
However, no alias have been declared and ALL the workflow that depend on them are not functional.

If an alias is declared for these nodes, the new implementation will be used.
And, at save time, old nodes will be replaced automatically by new nodes.

**Comment by christian34** [comment]
Okay. However I am not sure on how to declare such aliases, as it is not really a rename of a node but a move.
I've tried to add to the caribu/workflow/__wralea__ components factories aliases such as  (eg for LIE): 

LIE = CompositeNodeFactory(
name='LIE',
alias = ['alinea.caribu.LIE'], but this does not work!

Any idea ?

**Comment by pradal** [comment]
I am currently working on it.
I will send you a PR to review soon.
